### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Javascript

### ISSUE THREAD

**Issue by brunocalou** [stone-payments/vagas#13]
## Descrição da vaga

Desenvolver ferramentas em javascript, como clis, frameworks e bibliotecas

## Local

Escritório, Centro - Rio de Janeiro

## Requisitos

**Obrigatórios:**
- Bom conhecimento de javascript ES6
- Conhecimento de Nodejs
- Familiaridade com algum framework SPA, como Vue, React, etc.
- Familiaridade com API DOM

**Desejáveis:**
- Conhecimento em controle de versão com git

**Diferenciais:**
- Experiência em desenvolvimento de bibliotecas js
- Experiência em UX e design responsivo

## Nossa empresa

Aqui na Stone procuramos essencialmente pessoas com três características: inteligência, energia e integridade, independente da área de estudo do candidato. Assim, conhecimentos específicos não são impedimento para aplicar nas nossas oportunidades de emprego.

Mesmo que você não tenha os conhecimentos descritos na vaga, mas acha que é tudo a ver com a Stone, mande seu currículo anyway. :-)

## Observações

Não aceitamos home office

## Como se candidatar

Por favor envie um email para devpos@stone.com.br com seu CV anexado - enviar no assunto: `#DEV_JS ${SEU_NOME}`

**Comment by victorhcosta** [comment]
A vaga ainda está aberta?

**Comment by brunocalou** [comment]
@victorhcosta  Está sim
