### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor C/C++ para embarcado

### ISSUE THREAD

**Issue by danieldsdias** [stone-payments/vagas#4]
## Descrição da vaga

Desenvolvedor em linguagem C/C++ para Linux embarcado. Desenvolvimento de software para máquinas de pagamento com cartão.
## Local

Centro - Rio de Janeiro

## Requisitos

**Obrigatórios:**
- Conhecimento de linguagem C/C++
- Pro-atividade e comprometimento
- Domínio de conceitos de alocação dinâmica, ponteiros e estruturas em C.

**Desejáveis:**
- Conhecimento de padrões de projeto;
- Conhecimento em Controle de versão;
- Experiência com sistemas embarcados/Microcontroladores.

**Diferenciais:**
- Experiência com mercado de pagamentos;
- Conhecimento de desenvolvimento para POS;
- Desenvolvimento para Linux.
- Projetos opensource relacionados
## Nossa empresa

A Stone é a nova adquirente brasileira, criada para dar um fim na burocracia, mau atendimento e descaso que está presente hoje no mercado brasileiro de pagamentos. 

Aqui na Stone procuramos essencialmente pessoas com três características: inteligência, energia e integridade, independente da área de estudo do candidato. Assim, conhecimentos específicos não são impedimento para aplicar nas nossas oportunidades de emprego.

Mesmo que você não tenha os conhecimentos descritos na vaga, mas acha que é tudo a ver com a Stone, mande seu currículo anyway. :-)

Site: www.stone.com.br.
## Como se candidatar

Por favor envie um email para devpos@stone.com.br com seu CV anexado - enviar no assunto: `#DEV_CPP ${SEU_NOME}`

**Comment by luisbebop** [comment]
Quando conseguir contratar, pede para o time ajudar a gente aqui:

https://github.com/cloudwalkio/mruby-emv
https://github.com/cloudwalkio/main
https://github.com/cloudwalkio/da_funk
https://github.com/cloudwalkio/mruby-cloudwalk-platform
https://github.com/cloudwalkio/emv-sample

Também podemos dar vários insights para vocês aqui:

https://github.com/stone-pagamentos/pos-sdk/blob/master/source/images/Camadas.PNG
https://github.com/stone-pagamentos/pos-sdk/blob/master/source/index.md

Se a gente conseguir juntar forças, nossa solução conjunta pode ser muito melhor do que uma cópia.
