### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Front-end

### ISSUE THREAD

**Issue by lucianosantosdev** [stone-payments/vagas#8]
## Descrição da vaga
 
Desenvolvimento de interfaces para máquinas de pagamento com cartão.

## Local

Escritório, Centro - Rio de Janeiro

## Benefícios
- Vale refeição / alimentação
- Vale transporte
- Plano de saúde
- Seguro de vida
- Auxílio farmácia
- Auxílio creche
- horário flexível

## Requisitos

**Obrigatórios:**
- Conhecimento em desenvolvimento web básico: HTML5, CSS3 e JavaScript ES6
- Pro-atividade e comprometimento

**Desejáveis:**
- Experiência com algum framework SPA (Vue, Angular, React, ...)
- Design Responsivo
- UX design
- Conhecimento em Controle de versão;
- Conhecimento de padrões de projeto;

**Diferenciais:**
- Experiência com mercado de pagamentos;

## Nossa empresa

Aqui na Stone procuramos essencialmente pessoas com três características: inteligência, energia e integridade, independente da área de estudo do candidato. Assim, conhecimentos específicos não são impedimento para aplicar nas nossas oportunidades de emprego.

Mesmo que você não tenha os conhecimentos descritos na vaga, mas acha que é tudo a ver com a Stone, mande seu currículo anyway. :-)

## Como se candidatar

Por favor envie um email para ddias@stone.com.br com seu CV anexado - enviar no assunto: `#FRONT_POS ${SEU_NOME}`

**Comment by JonasEmanuel** [comment]
Enviado :) 
Eu já fiz entrevista com vocês a mais de 4 meses, conforme está no site, segue meu CPF 14470781797.
