### ISSUE TITLE
[Rio de Janeiro] Front-End Developer 

### ISSUE THREAD

**Issue by Lucasktrindade** [stone-payments/vagas#9]
## Descrição da vaga

Desenvolvimento de aplicações SPA. Abaixo alguns conhecimentos que esperamos de você:

## Local

Escritório Rio de Janeiro - Av. General Justo, 375 - Centro, Rio de Janeiro.

## Requisitos

**Obrigatórios:**
- CSS3
- HTML5
- Javascript
- ES6
- API RESTful
- Experiência com SPA's(AngularJS, Vue.js ou React)
- Git

**Desejáveis:**
- Experiência com testes
- Design Patterns em JS
- Ter trabalhado com metodologias ágeis (Scrum)
- Conhecimentos sobre Progressive Web Apps

## Contratação

A combinar

## Nossa empresa

A Stone é uma entidade que está licenciada para processar pagamentos eletrônicos em todo território nacional, no mundo físico e virtual.

Nosso propósito é melhorar a vida do empreendedor através de tecnologias no mercado de pagamentos.

Em um mercado que por muito tempo foi desrespeitoso com o cliente, nós nascemos para fazer a diferença na vida do lojista brasileiro através da tecnologia e do bom atendimento. 

Mais informações: [https://enter.stone.com.br/](https://enter.stone.com.br/)

## Como se candidatar

Por favor envie um email para ltrindade@stone.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by JonasEmanuel** [comment]
Enviado

**Comment by JonasEmanuel** [comment]
Enviado :)
Eu já fiz entrevista com vocês a mais de 4 meses, conforme está no site, segue meu CPF 14470781797.

**Comment by victorhcosta** [comment]
A vaga ainda está aberta?

**Comment by munirwanis** [comment]
@victorhcosta está sim!
